baseURL = "https://khaledaxeldjebbari.github.io/"
languageCode = "en-us"
title = "Khaled Axel Djebbari"
theme = "academia-hugo"

# ----------------------------------------
# FORCE DISABLE COMMENTS (DISQUS)
# ----------------------------------------
[services]
  [services.disqus]
    shortname = ""

# Hugo-wide kill switch
disableKinds = ["RSS"]
